name: alice_test
description: "Test utils for Alice packages."
version: 1.0.1
homepage: https://github.com/jhomlala/alice
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  alice:
  test: ^1.25.7
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
